config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root 'articles#index'

  get 'terms'=>'single_pages#terms'
  get 'about'=>'single_pages#about'

  get 'contacts'=>'contacts#new'
  
  resource :contacts, only: [:new, :create]

  resources :articles do
    resources :comments, only: [:create]
  end

end

app/models/article.rb
# статья в блоге

class Article < ActiveRecord::Base
  validates :title, :text, presence: true
  validates :title, length: { maximum: 140 }
  validates :text, length: { maximum: 4000 }
  # статья может иметь много комментариев
  has_many :comments

  # возвращает заголовок статьи
  def subject
    title
  end

  # возвращает последний комментарий
  def last_comment
    comments.last
  end
end

app/models/comment.rb
# комментарий к статье в блоге

class Comment < ActiveRecord::Base
  validates :author, :body, presence: true
  validates :body, length: { maximum: 4000 }
  # комментарий привязан к одной статье
  belongs_to :article
end

app/models/contact.rb
# сообщение

class Contact < ActiveRecord::Base
  validates :message, presence: true
  validates :email, format: {with: /@/}
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  # для контроллера devise вызываем метод, который определет разрешенные 
  # к передаче из формы параметры
  before_action :configure_permitted_parameters, if: :devise_controller?

  # переопределяем метод devise, чтобы после выхода оставаться на той же странице
  def after_sign_out_path_for(resource_or_scope)
    request.referrer || root_path
  end

  after_filter :store_location

  def store_location
    # store last url - this is needed for post-login redirect to whatever the user last visited.
    return unless request.get? 
    if (request.path != "/users/sign_in" &&
        request.path != "/users/sign_up" &&
        request.path != "/users/password/new" &&
        request.path != "/users/password/edit" &&
        request.path != "/users/confirmation" &&
        request.path != "/users/sign_out" &&
        !request.xhr?) # don't store ajax calls
      session[:previous_url] = request.fullpath 
    end
  end

  # переопределяем метод devise, чтобы после входа оставаться на той же странице
  def after_sign_in_path_for(resource)
    session[:previous_url] || root_path
  end

  protected
  # к разрешенным параметрам для devise добавляем параметр :username
  def configure_permitted_parameters
     devise_parameter_sanitizer.permit(:sign_up, keys: [:username])
     devise_parameter_sanitizer.permit(:sign_in, keys: [:username])
     devise_parameter_sanitizer.permit(:account_update, keys: [:username])
  end 
end

app/controllers/articles_controller.rb
# статьи в блоге
class ArticlesController < ApplicationController

  # за исключением просмотра, все остальные действия требуют аутентификации пользователя
  before_action :authenticate_user!, :except => [:show, :index]

	def new
	end

  def index
    @articles=Article.order(:updated_at).reverse
  end

  def show
    @article=Article.find(params[:id])
    @comments=@article.comments.order(:created_at).reverse
  end

 	def create
    @article=Article.new(article_params)
    @article.author=current_user.username
    # если статью удается записать, то выводится записанная статья, иначе - снова форма создания статьи
    if @article.save then
      redirect_to @article
    else
      render action: 'new'
    end
  end

  def edit
    @article=Article.find(params[:id])
  end

  def update
    @article=Article.find(params[:id])

    # если статью удается записать, то выводится записанная статья, иначе - снова форма редактирования статьи
    if @article.update(article_params)
      redirect_to @article
    else
      render action: 'edit'
    end
  end

  def destroy
    Article.find(params[:id]).destroy
    redirect_to articles_path
  end

  private

  # разрешение передачи парметров
  def article_params
    params.require(:article).permit(:title, :text, :author)
  end

end

app/controllers/comments_controller.rb
# комментарии к статьям в блоге
class CommentsController < ApplicationController

  before_filter :authenticate_user!

	# реализовано только создание комментариев
	# вывод комментариев происходит в виде вывода статьи
	def create
		@article=Article.find(params[:article_id])
		@article.comments.create(comment_params)
		redirect_to @article
	end

	private

	# разрешение передачи параметров
	def comment_params
  	params.require(:comment).permit(:author, :body)
	end


end

app/controllers/contacts_controller.rb
# отправка сообщений
class ContactsController < ApplicationController

	def new
	end

	def create
    @contact=Contact.new(contact_params)

    # если новое сообщение валидно, оно записывается, иначе снова вызывается форма ввода
    if @contact.valid? then
      @contact.save
    else
      render action: 'new'
    end
	end

  private

  # разрешение передачи параметров
  def contact_params
    params.require(:contact).permit(:email, :message)
  end
	
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/single_pages_controller.rb
# контроллер ответственный за одиночные страницы вне модели REST 
class SinglePagesController < ApplicationController

  def terms
  end

  def about
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/single_pages_helper.rb
module SinglePagesHelper
end

app/views/about/show.html.erb
<h1>About MyRORBlog</h1>
<p>It is my simple blog for the very smart ideas.... </p>
<p>Whoooooooo, hooooooooooo, hooooooooooo!</p>

app/views/articles/edit.html.erb
<!-- редактирование статьи -->
<h1>Edit article #<%= @article.id %></h1>

<% if @article.author==current_user.username %>
	<%= form_for @article do |f| %>

		<p>
			<%= f.label :title %><br>
			<%= f.text_field :title %>
		</p>

		<p>
			<%= f.label :text %><br>
			<%= f.text_area :text %>
		</p>

		<p>
			<%= f.submit %>
		</p>

	<% end %>
<% else %>
	<p>You can not edit the article. Please login.</p>
<% end %>

app/views/articles/index.html.erb
<!-- список статей -->
<h1>All articles</h1>

<!-- ссылка на создание новой статьи -->
<% if user_signed_in? %>
	<%= link_to ">>> Create new Article <<<", new_article_path %>
<% end %>
<% @articles.each do |item| %>
	<article>
		<hr>
		<h2><%= link_to item.title, article_path(item) %></h2>
		<small>posted at <%= item.created_at %> <% if item.created_at!=item.updated_at %>/ updated at <%= item.updated_at %><% end %></small>
		<p><%= simple_format(item.text) %></p>

		<!-- ссылки на редактирование и удаление (с подтверждением) -->
		<% if (user_signed_in?) && (current_user.username==item.author) %>
			<small><%= link_to ">>> Edit", edit_article_path(item) %> | <%= link_to "Delete <<<", article_path(item), method: :delete, data: {confirm: "Are you shure?"} %></small>
		<% end %>
	</article>	
<% end %>

app/views/articles/new.html.erb
<!-- создание новой статьи -->
<h1>Add new article</h1>

<%= form_for :article, url: articles_path do |f| %>

	<!-- вывод списка ошибок верификации -->
	<% if @article %>
		<i>
		<ul>
		<% @article.errors.full_messages.each do |item| %>
			<li><%= item+'!' %></li>
		<% end %>
		</ul>
		</i>
	<% end %>

	<p>
		<%= f.label :title %><br>
		<%= f.text_field :title, style: "width:100%" %>
	</p>

	<p>
		<%= f.label :text %><br>
		<%= f.text_area :text, style: "width:100%" %>
	</p>

	<p>
		<%= f.submit %>
	</p>

<% end %>

app/views/articles/show.html.erb
<!-- вывод одной статьи, списка комментариев к ней и ввод нового комментария -->
<h1>Article #<%= @article.id %></h1>
<hr>
<h2><%= @article.title %> </h2>
<small>posted at <%= @article.created_at %> / updated at <%= @article.updated_at %></small>
<p><%= simple_format(@article.text) %></p>

<!-- ссылка на вывод списка статей -->
<small><%= link_to "Show all articles", articles_path %></small>
<hr>

<!-- список комментариев -->
<h3>Comments:</h3>
<% @comments.each do |item| %>
	<strong><%= item.created_at%> <%= item.author %> wrote:<br></strong>
	<%= simple_format(item.body) %><br>
<% end %>
<hr>
<!-- если юзер залогинен - разрешаем вводить комментарии -->
<% if user_signed_in? %>
	<!-- форма ввода комментариев -->
	<h3>Add comment:</h3>
	<!-- форма для ввода связанных сущностей, причем несуществующий еще объект comments создается пустым с помощью метода build -->
	<%= form_for [@article, @article.comments.build] do |f| %>

		<p>
			<%= f.label :author %><br>
			<%= f.text_field :author, :value => current_user.username, :readonly => true %>
		</p>

		<p>
			<%= f.label :body %><br>
			<%= f.text_area :body, style: "width:100%" %>
		</p>

		<p>
			<%= f.submit %>
		</p>

	<% end %>
<!-- если не залогинен - просим залогинится -->
<% else %>
	<p>For enter comments, please <%= link_to "Log In", new_user_session_path %></p>
<% end %>

app/views/contacts/create.html.erb
<h1>Thanks you!</h1>

app/views/contacts/new.html.erb
<!-- ввод нового сообщения -->
<h1><%= t('contact.add_new_mess') %></h1>

<%= form_for :contact, url: contacts_path do |f| %>

	<!-- вывод списка ошибок верификации -->
	<% if @contact %>
		<i>
		<ul>
		<% @contact.errors.full_messages.each do |item| %>
			<li><%= item+'!' %></li>
		<% end %>
		</ul>
		</i>
	<% end %>
	
	<p>
		<%= f.label :email, "E-mail" %><br>
		<%= f.text_field :email %>
	</p>

	<p>
		<%= f.label :message %><br>
		<%= f.text_area :message, style: "width:100%" %>
	</p>

	<p>
		<%= f.submit 'Send message' %>
	</p>

<% end %>

app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>

app/views/layouts/application.html.erb
<!-- основной шаблон -->
<!DOCTYPE html>
<html>
<head>
  <!-- подключаем bootstrap -->
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
  <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
  <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
  <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
    <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
  <![endif]-->

  <title>MyRORBlog</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class="container">
  <!-- навигационная панель -->
  <div class="row">
      <nav class="col-xs-8">
        <br>
        <a href='/articles'>Articles</a> |
      	<a href='/contacts'>Contacts</a> |
      	<a href='/about'>About us</a> |
      	<a href='/terms'>Terms of use</a>
      </nav> <!-- col -->
      <nav class="col-xs-4 text-right">
        <br>
        <!-- если пользователь вошел в систему -->
        <% if user_signed_in? %>
          <span>Hello, <%= current_user.username %>! |</span>
          <%= link_to "Log Out", destroy_user_session_path, method: :delete %>
        <!-- и если не вошел -->
        <% else %>
          <%= link_to "Log In", new_user_session_path %>
        <% end %>
      </nav> <!-- col -->
  </div> <!-- row -->
  <div class="row">
    <div class="col-xs-12">
      <hr>
    </div>
  </div> <!-- row -->

  <!-- сообщения и предупреждения -->
  <% if notice %>
    <div class="row">
      <div class="col-xs-12">
        <div class="alert alert-info fade in">
          <a href="#" class="close" data-dismiss="alert">&times;</a>
          <span class="glyphicon glyphicon-info-sign"></span>
          <%= notice %>
        </div>
      </div> <!-- col -->
    </div> <!-- row -->
  <% end %>

  <!-- вывод постов -->
  <div class="row">
    <div class="col-xs-12">
      <%= yield %>
    </div> <!-- col -->
  </div> <!-- row -->
</div> <!-- container -->

<!-- подключаем jquery и bootstrap -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
</body>
</html>

app/views/single_pages/about.html.erb
<h1>About MyRORBlog</h1>
<p>It is my simple blog for the very smart ideas.... </p>
<p>Whoooooooo, hooooooooooo, hooooooooooo!</p>

app/views/single_pages/terms.html.erb
<h1>Terms and Conditions ("Terms")</h1>
<p>Last updated: July 02, 2016</p>
<p>Please read these Terms and Conditions ("Terms", "Terms and Conditions") carefully before using the http://myrorblog.com.ua website (the "Service") operated by MyRORBlog ("us", "we", or "our").</p>
<p>Your access to and use of the Service is conditioned on your acceptance of and compliance with these Terms. These Terms apply to all visitors, users and others who access or use the Service.</p>
<p>By accessing or using the Service you agree to be bound by these Terms. If you disagree with any part of the terms then you may not access the Service.</p>
<p><strong>Accounts</strong></p>
<p>When you create an account with us, you must provide us information that is accurate, complete, and current at all times. Failure to do so constitutes a breach of the Terms, which may result in immediate termination of your account on our Service.</p>
<p>You are responsible for safeguarding the password that you use to access the Service and for any activities or actions under your password, whether your password is with our Service or a third-party service.</p>
<p>You agree not to disclose your password to any third party. You must notify us immediately upon becoming aware of any breach of security or unauthorized use of your account.</p>
<p><strong>Links To Other Web Sites</strong></p>
<p>Our Service may contain links to third-party web sites or services that are not owned or controlled by MyRORBlog.</p>
<p>MyRORBlog has no control over, and assumes no responsibility for, the content, privacy policies, or practices of any third party web sites or services. You further acknowledge and agree that MyRORBlog shall not be responsible or liable, directly or indirectly, for any damage or loss caused or alleged to be caused by or in connection with use of or reliance on any such content, goods or services available on or through any such web sites or services.</p>
<p>We strongly advise you to read the terms and conditions and privacy policies of any third-party web sites or services that you visit.</p>
<p><strong>Termination</strong></p>
<p>We may terminate or suspend access to our Service immediately, without prior notice or liability, for any reason whatsoever, including without limitation if you breach the Terms.</p>
<p>All provisions of the Terms which by their nature should survive termination shall survive termination, including, without limitation, ownership provisions, warranty disclaimers, indemnity and limitations of liability.</p>
<p>We may terminate or suspend your account immediately, without prior notice or liability, for any reason whatsoever, including without limitation if you breach the Terms.</p>
<p>Upon termination, your right to use the Service will immediately cease. If you wish to terminate your account, you may simply discontinue using the Service.</p>
<p>All provisions of the Terms which by their nature should survive termination shall survive termination, including, without limitation, ownership provisions, warranty disclaimers, indemnity and limitations of liability.</p>
<p><strong>Governing Law</strong></p>
<p>These Terms shall be governed and construed in accordance with the laws of Ukraine, without regard to its conflict of law provisions.</p>
<p>Our failure to enforce any right or provision of these Terms will not be considered a waiver of those rights. If any provision of these Terms is held to be invalid or unenforceable by a court, the remaining provisions of these Terms will remain in effect. These Terms constitute the entire agreement between us regarding our Service, and supersede and replace any prior agreements we might have between us regarding the Service.</p>
<p><strong>Changes</strong></p>
<p>We reserve the right, at our sole discretion, to modify or replace these Terms at any time. If a revision is material we will try to provide at least 30 days notice prior to any new terms taking effect. What constitutes a material change will be determined at our sole discretion.</p>
<p>By continuing to access or use our Service after those revisions become effective, you agree to be bound by the revised terms. If you do not agree to the new terms, please stop using the Service.</p>
<p><strong>Contact Us</strong></p>
<p>If you have any questions about these Terms, please contact us.</p>

app/views/terms/show.html.erb
<h1>Terms and Conditions ("Terms")</h1>
<p>Last updated: July 02, 2016</p>
<p>Please read these Terms and Conditions ("Terms", "Terms and Conditions") carefully before using the http://myrorblog.com.ua website (the "Service") operated by MyRORBlog ("us", "we", or "our").</p>
<p>Your access to and use of the Service is conditioned on your acceptance of and compliance with these Terms. These Terms apply to all visitors, users and others who access or use the Service.</p>
<p>By accessing or using the Service you agree to be bound by these Terms. If you disagree with any part of the terms then you may not access the Service.</p>
<p><strong>Accounts</strong></p>
<p>When you create an account with us, you must provide us information that is accurate, complete, and current at all times. Failure to do so constitutes a breach of the Terms, which may result in immediate termination of your account on our Service.</p>
<p>You are responsible for safeguarding the password that you use to access the Service and for any activities or actions under your password, whether your password is with our Service or a third-party service.</p>
<p>You agree not to disclose your password to any third party. You must notify us immediately upon becoming aware of any breach of security or unauthorized use of your account.</p>
<p><strong>Links To Other Web Sites</strong></p>
<p>Our Service may contain links to third-party web sites or services that are not owned or controlled by MyRORBlog.</p>
<p>MyRORBlog has no control over, and assumes no responsibility for, the content, privacy policies, or practices of any third party web sites or services. You further acknowledge and agree that MyRORBlog shall not be responsible or liable, directly or indirectly, for any damage or loss caused or alleged to be caused by or in connection with use of or reliance on any such content, goods or services available on or through any such web sites or services.</p>
<p>We strongly advise you to read the terms and conditions and privacy policies of any third-party web sites or services that you visit.</p>
<p><strong>Termination</strong></p>
<p>We may terminate or suspend access to our Service immediately, without prior notice or liability, for any reason whatsoever, including without limitation if you breach the Terms.</p>
<p>All provisions of the Terms which by their nature should survive termination shall survive termination, including, without limitation, ownership provisions, warranty disclaimers, indemnity and limitations of liability.</p>
<p>We may terminate or suspend your account immediately, without prior notice or liability, for any reason whatsoever, including without limitation if you breach the Terms.</p>
<p>Upon termination, your right to use the Service will immediately cease. If you wish to terminate your account, you may simply discontinue using the Service.</p>
<p>All provisions of the Terms which by their nature should survive termination shall survive termination, including, without limitation, ownership provisions, warranty disclaimers, indemnity and limitations of liability.</p>
<p><strong>Governing Law</strong></p>
<p>These Terms shall be governed and construed in accordance with the laws of Ukraine, without regard to its conflict of law provisions.</p>
<p>Our failure to enforce any right or provision of these Terms will not be considered a waiver of those rights. If any provision of these Terms is held to be invalid or unenforceable by a court, the remaining provisions of these Terms will remain in effect. These Terms constitute the entire agreement between us regarding our Service, and supersede and replace any prior agreements we might have between us regarding the Service.</p>
<p><strong>Changes</strong></p>
<p>We reserve the right, at our sole discretion, to modify or replace these Terms at any time. If a revision is material we will try to provide at least 30 days notice prior to any new terms taking effect. What constitutes a material change will be determined at our sole discretion.</p>
<p>By continuing to access or use our Service after those revisions become effective, you agree to be bound by the revised terms. If you do not agree to the new terms, please stop using the Service.</p>
<p><strong>Contact Us</strong></p>
<p>If you have any questions about these Terms, please contact us.</p>